# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-service-docker-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registrynameis.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6aa7bba6ea7a4d25baa8eb5fd04c1349 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_048de627bd2f4af8804cf97f9eeab9c5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registrynameis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6aa7bba6ea7a4d25baa8eb5fd04c1349 }}/First-Image-is:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-service-docker-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_47ef5246b590441f829e7d0bf03523f5 }}
        images: 'registrynameis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6aa7bba6ea7a4d25baa8eb5fd04c1349 }}/First-Image-is:${{ github.sha }}'