# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - demo-java-docker-aap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myfirstregistrydemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_382f686588bb43bda940cf6739ffe896 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fb18aed87e0b442087751699097c1482 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myfirstregistrydemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_382f686588bb43bda940cf6739ffe896 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'demo-java-docker-aap'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_caa40005e8a04637857da4465b3a0643 }}
        images: 'myfirstregistrydemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_382f686588bb43bda940cf6739ffe896 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'